id: P000467
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-16 15:41:27.008045
source_metadata:
  id: bdr:W1KG22690
  title: བོད་དབྱིན་ཚིག་མཛོད།
  author: ''
  volumes:
    994a7d97b6e94d87b2bda4025fc58da8:
      image_group_id: I1KG22732
      title: Volume 1 of bod dbyn mdzod mdzod/
      volume_number: 1
      total_pages: 1278
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
